### ISSUE TITLE
dev : add the ability to retrieve future entries through data endpoint

### ISSUE THREAD

**Issue by azurwastaken** [astraly-labs/pragma-node#72]
Currently we are only able to retrieve spot entries from the offchain api while populating its db with spot and future.

The purpose of this issue is to be able to query future entries also.

## TODO

- [X] be able to retrieve a price from future
- [ ] move this to a new data/future route
- [ ] add a new optionnal parameter expiry_date with default = 0 (PERP) that allow to get a price filtered by expiry date
- [ ] add a new route data/future/expiries that return a list of available expiries
